USE PBL3;
CREATE TABLE ActivityLog(
	id_log INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    action NVARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

USE PBL3;
DROP TABLE ActivityLog;