USE PBL3;
CREATE TABLE ProductLog (
    LogID       INT AUTO_INCREMENT PRIMARY KEY,
    ProductID   INT NOT NULL,
    ProductName NVARCHAR(100) NOT NULL,
    Action      ENUM('ADD', 'UPDATE', 'RESTART_BUSINESS', 'STOP_BUSINESS') NOT NULL,
    ActionTime  DATETIME DEFAULT CURRENT_TIMESTAMP,
    Note        NVARCHAR(255),

    FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);
USE PBL3;
DROP TABLE ProductLog;
